{
    "url": "https://api.github.com/repos/pallets/flask/issues/1047",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1047/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1047/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1047/events",
    "html_url": "https://github.com/pallets/flask/issues/1047",
    "id": 32864503,
    "node_id": "MDU6SXNzdWUzMjg2NDUwMw==",
    "number": 1047,
    "title": "testsuite status, 0.10.; FAILED (failures=3, errors=2)",
    "user": {
        "login": "idella",
        "id": 1655078,
        "node_id": "MDQ6VXNlcjE2NTUwNzg=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/1655078?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/idella",
        "html_url": "https://github.com/idella",
        "followers_url": "https://api.github.com/users/idella/followers",
        "following_url": "https://api.github.com/users/idella/following{/other_user}",
        "gists_url": "https://api.github.com/users/idella/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/idella/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/idella/subscriptions",
        "organizations_url": "https://api.github.com/users/idella/orgs",
        "repos_url": "https://api.github.com/users/idella/repos",
        "events_url": "https://api.github.com/users/idella/events{/privacy}",
        "received_events_url": "https://api.github.com/users/idella/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2014-05-06T03:49:47Z",
    "updated_at": "2014-05-07T19:43:33Z",
    "closed_at": "2014-05-07T19:43:33Z",
    "author_association": "NONE",
    "body": "with pypy; $ pypy -V\nPython 2.7.3 (87aa9de10f9ca71da9ab4a3d53e0ba176b67d086, Apr 09 2014, 00:32:56) [PyPy 2.2.1]\n\n``` python\n * pypy: running distutils-r1_run_phase python_test\n............E...............................................................................................................F..........................F.............................F......................................E............\n======================================================================\nERROR: test_build_error_handler (flask.testsuite.basic.BasicFunctionalityTestCase)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/basic.py\", line 758, in test_build_error_handler\n    flask.url_for('spam')\nTypeError: exceptions must be old-style classes or derived from BaseException, not NoneType\n\n======================================================================\nERROR: test_session_transactions_no_null_sessions (flask.testsuite.testing.TestToolsTestCase)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/testing.py\", line 106, in test_session_transactions_no_null_sessions\n    with c.session_transaction() as sess:\nTypeError: exceptions must be old-style classes or derived from BaseException, not NoneType\n\n======================================================================\nFAIL: test_uninstalled_package_paths (flask.testsuite.config.InstanceTestCase)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/config.py\", line 167, in test_uninstalled_package_paths\n    self.assert_equal(app.instance_path, os.path.join(here, 'test_apps', 'instance'))\n  File \"/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/__init__.py\", line 139, in assert_equal\n    return self.assertEqual(x, y)\nAssertionError: '/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/test_apps/config_package_app/instance' != '/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/test_apps/instance'\n\n======================================================================\nFAIL: test_json_key_sorting (flask.testsuite.helpers.JSONTestCase)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/helpers.py\", line 200, in test_json_key_sorting\n    '}'\n  File \"/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/__init__.py\", line 139, in assert_equal\n    return self.assertEqual(x, y)\nAssertionError: Lists differ: [u'{', u'\"values\": {', u'\"0\": ... != ['{', '\"values\": {', '\"0\": \"fo...\n\nFirst differing element 4:\n\"10\": \"foo\",\n\"2\": \"foo\",\n\nDiff is 955 characters long. Set self.maxDiff to None to see it.\n\n======================================================================\nFAIL: test_appcontext_signals (flask.testsuite.signals.SignalsTestCase)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/signals.py\", line 118, in test_appcontext_signals\n    self.assert_equal(recorded, ['push', 'pop'])\n  File \"/mnt/gen2/TmpDir/portage/dev-python/flask-0.10.1-r1/work/Flask-0.10.1/flask/testsuite/__init__.py\", line 139, in assert_equal\n    return self.assertEqual(x, y)\nAssertionError: Lists differ: ['push', 'push'] != ['push', 'pop']\n\nFirst differing element 1:\npush\npop\n\n- ['push', 'push']\n?            ^^^\n\n+ ['push', 'pop']\n?            ^^\n\n\n----------------------------------------------------------------------\nRan 233 tests in 5.798s\n\nFAILED (failures=3, errors=2)\n```\n\nditto py2.7 3.3. Not got deps installed under py3.4 at this stage.\nTo me it appears the tests are simply written for py2 py3 and pypy misses out because of how pypy selects and or uses exception classes in case of the errors triggered by these tests. As for the failures=3, well, 1 is a unicode issue, the others just don't work.\n\nOh. see 837\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/42473815",
            "html_url": "https://github.com/pallets/flask/issues/1047#issuecomment-42473815",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1047",
            "id": 42473815,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQyNDczODE1",
            "user": {
                "login": "mitsuhiko",
                "id": 7396,
                "node_id": "MDQ6VXNlcjczOTY=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/7396?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mitsuhiko",
                "html_url": "https://github.com/mitsuhiko",
                "followers_url": "https://api.github.com/users/mitsuhiko/followers",
                "following_url": "https://api.github.com/users/mitsuhiko/following{/other_user}",
                "gists_url": "https://api.github.com/users/mitsuhiko/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mitsuhiko/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mitsuhiko/subscriptions",
                "organizations_url": "https://api.github.com/users/mitsuhiko/orgs",
                "repos_url": "https://api.github.com/users/mitsuhiko/repos",
                "events_url": "https://api.github.com/users/mitsuhiko/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mitsuhiko/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-05-07T19:43:33Z",
            "updated_at": "2014-05-07T19:43:33Z",
            "author_association": "MEMBER",
            "body": "Works for me.  This might be the pypy bug again that I already work around in the unreleased version of Flask.\n"
        }
    ]
}