{
    "url": "https://api.github.com/repos/pallets/flask/issues/1069",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1069/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1069/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1069/events",
    "html_url": "https://github.com/pallets/flask/issues/1069",
    "id": 34240659,
    "node_id": "MDU6SXNzdWUzNDI0MDY1OQ==",
    "number": 1069,
    "title": "Flask re-raise exception that already been processed.",
    "user": {
        "login": "honglei",
        "id": 1011330,
        "node_id": "MDQ6VXNlcjEwMTEzMzA=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/1011330?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/honglei",
        "html_url": "https://github.com/honglei",
        "followers_url": "https://api.github.com/users/honglei/followers",
        "following_url": "https://api.github.com/users/honglei/following{/other_user}",
        "gists_url": "https://api.github.com/users/honglei/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/honglei/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/honglei/subscriptions",
        "organizations_url": "https://api.github.com/users/honglei/orgs",
        "repos_url": "https://api.github.com/users/honglei/repos",
        "events_url": "https://api.github.com/users/honglei/events{/privacy}",
        "received_events_url": "https://api.github.com/users/honglei/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 5,
    "created_at": "2014-05-24T19:21:21Z",
    "updated_at": "2014-05-27T16:48:11Z",
    "closed_at": "2014-05-27T16:48:11Z",
    "author_association": "NONE",
    "body": "## I get an an error during request to a static html file.\n\nserving on http://0.0.0.0:8080\nERROR:**main**:Exception on /static/bloggr-client/index.html [GET]\nTraceback (most recent call last):\n  File \"c:\\users\\honglei\\appdata\\local\\enthought\\canopy\\user\\lib\\site-packages\\flask\\app.py\", line 1898, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"c:\\users\\honglei\\appdata\\local\\enthought\\canopy\\user\\lib\\site-packages\\flask\\app.py\", line 1553, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"c:\\users\\honglei\\appdata\\local\\enthought\\canopy\\user\\lib\\site-packages\\flask\\app.py\", line 1457, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"c:\\users\\honglei\\appdata\\local\\enthought\\canopy\\user\\lib\\site-packages\\flask\\app.py\", line 1551, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"c:\\users\\honglei\\appdata\\local\\enthought\\canopy\\user\\lib\\site-packages\\flask\\app.py\", line 1537, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"c:\\users\\honglei\\appdata\\local\\enthought\\canopy\\user\\lib\\site-packages\\flask\\helpers.py\", line 872, in send_static_file\n    cache_timeout=cache_timeout)\n  File \"c:\\users\\honglei\\appdata\\local\\enthought\\canopy\\user\\lib\\site-packages\\flask\\helpers.py\", line 623, in send_from_directory\n    return send_file(filename, **options)\n  File \"c:\\users\\honglei\\appdata\\local\\enthought\\canopy\\user\\lib\\site-packages\\flask\\helpers.py\", line 498, in send_file\n    mimetype = mimetypes.guess_type(filename or attachment_filename)[0]\n  File \"C:\\Users\\honglei\\AppData\\Local\\Enthought\\Canopy\\App\\appdata\\canopy-1.3.0.1715.win-x86_64\\lib\\mimetypes.py\", line 297, in guess_type\n    init()\n  File \"C:\\Users\\honglei\\AppData\\Local\\Enthought\\Canopy\\App\\appdata\\canopy-1.3.0.1715.win-x86_64\\lib\\mimetypes.py\", line 358, in init\n    db.read_windows_registry()\n  File \"C:\\Users\\honglei\\AppData\\Local\\Enthought\\Canopy\\App\\appdata\\canopy-1.3.0.1715.win-x86_64\\lib\\mimetypes.py\", line 258, in read_windows_registry\n    for subkeyname in enum_types(hkcr):\n  File \"C:\\Users\\honglei\\AppData\\Local\\Enthought\\Canopy\\App\\appdata\\canopy-1.3.0.1715.win-x86_64\\lib\\mimetypes.py\", line 249, in enum_types\n    ctype = ctype.encode(default_encoding) # omit in 3.x!\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal not in range(128)\n\nctype's value\n'.\\xb0\\xa2\\xc0\\xef\\xcd\\xfa\\xcd\\xfa\\xbd\\xd3\\xca\\xd5\\xb5\\xc4\\xbf\\xc9\\xd2\\xc9\\xce\\xc4\\xbc\\xfe'\n\nI don't think a unkown ctype in Windows's registry should cause Flask give up user's request.\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/44097072",
            "html_url": "https://github.com/pallets/flask/issues/1069#issuecomment-44097072",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1069",
            "id": 44097072,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MDk3MDcy",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-05-24T19:24:45Z",
            "updated_at": "2014-05-24T19:24:45Z",
            "author_association": "MEMBER",
            "body": "That looks like a bug or garbage-in-garbage-out behaviour in the mimetypes module.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/44098555",
            "html_url": "https://github.com/pallets/flask/issues/1069#issuecomment-44098555",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1069",
            "id": 44098555,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MDk4NTU1",
            "user": {
                "login": "danielchatfield",
                "id": 1058676,
                "node_id": "MDQ6VXNlcjEwNTg2NzY=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/1058676?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/danielchatfield",
                "html_url": "https://github.com/danielchatfield",
                "followers_url": "https://api.github.com/users/danielchatfield/followers",
                "following_url": "https://api.github.com/users/danielchatfield/following{/other_user}",
                "gists_url": "https://api.github.com/users/danielchatfield/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/danielchatfield/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/danielchatfield/subscriptions",
                "organizations_url": "https://api.github.com/users/danielchatfield/orgs",
                "repos_url": "https://api.github.com/users/danielchatfield/repos",
                "events_url": "https://api.github.com/users/danielchatfield/events{/privacy}",
                "received_events_url": "https://api.github.com/users/danielchatfield/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-05-24T20:11:43Z",
            "updated_at": "2014-05-24T20:11:43Z",
            "author_association": "NONE",
            "body": "You are using the canopy distro of python and the bug is inside its `mimetypes.py` file, it is possible that the same bug exists in the standard library version of mimetypes - if so I suggest making a bug on the python bug tracker, this is not a problem with Flask though.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/44283777",
            "html_url": "https://github.com/pallets/flask/issues/1069#issuecomment-44283777",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1069",
            "id": 44283777,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MjgzNzc3",
            "user": {
                "login": "honglei",
                "id": 1011330,
                "node_id": "MDQ6VXNlcjEwMTEzMzA=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1011330?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/honglei",
                "html_url": "https://github.com/honglei",
                "followers_url": "https://api.github.com/users/honglei/followers",
                "following_url": "https://api.github.com/users/honglei/following{/other_user}",
                "gists_url": "https://api.github.com/users/honglei/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/honglei/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/honglei/subscriptions",
                "organizations_url": "https://api.github.com/users/honglei/orgs",
                "repos_url": "https://api.github.com/users/honglei/repos",
                "events_url": "https://api.github.com/users/honglei/events{/privacy}",
                "received_events_url": "https://api.github.com/users/honglei/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-05-27T14:31:33Z",
            "updated_at": "2014-05-27T14:31:33Z",
            "author_association": "NONE",
            "body": "Even though it is not Flask's problem, I hope Flash can catch it, surround the mimetypes.guess_type. If mimetypes.guess_type  cannot guess it, we should continue to return the file rather than break down.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/44285116",
            "html_url": "https://github.com/pallets/flask/issues/1069#issuecomment-44285116",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1069",
            "id": 44285116,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0Mjg1MTE2",
            "user": {
                "login": "danielchatfield",
                "id": 1058676,
                "node_id": "MDQ6VXNlcjEwNTg2NzY=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/1058676?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/danielchatfield",
                "html_url": "https://github.com/danielchatfield",
                "followers_url": "https://api.github.com/users/danielchatfield/followers",
                "following_url": "https://api.github.com/users/danielchatfield/following{/other_user}",
                "gists_url": "https://api.github.com/users/danielchatfield/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/danielchatfield/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/danielchatfield/subscriptions",
                "organizations_url": "https://api.github.com/users/danielchatfield/orgs",
                "repos_url": "https://api.github.com/users/danielchatfield/repos",
                "events_url": "https://api.github.com/users/danielchatfield/events{/privacy}",
                "received_events_url": "https://api.github.com/users/danielchatfield/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-05-27T14:41:36Z",
            "updated_at": "2014-05-27T14:41:36Z",
            "author_association": "NONE",
            "body": "@honglei Flask shouldn't do that - firstly returning a file with an incorrect mimetype is pretty useless (CSS and JS will not work with an incorrect mimetype).\n\nFlask does catch it and returns a 500, that is what the 500 is for - a server error which is what this is.\n\nYou have a bug in both your environment (your registry contains invalid mimetypes) and are using a non-standard python distro that fails to handle this. Silently handling exceptions is incredibly bad practice as it makes debugging impossible.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/44302566",
            "html_url": "https://github.com/pallets/flask/issues/1069#issuecomment-44302566",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1069",
            "id": 44302566,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MzAyNTY2",
            "user": {
                "login": "honglei",
                "id": 1011330,
                "node_id": "MDQ6VXNlcjEwMTEzMzA=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1011330?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/honglei",
                "html_url": "https://github.com/honglei",
                "followers_url": "https://api.github.com/users/honglei/followers",
                "following_url": "https://api.github.com/users/honglei/following{/other_user}",
                "gists_url": "https://api.github.com/users/honglei/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/honglei/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/honglei/subscriptions",
                "organizations_url": "https://api.github.com/users/honglei/orgs",
                "repos_url": "https://api.github.com/users/honglei/repos",
                "events_url": "https://api.github.com/users/honglei/events{/privacy}",
                "received_events_url": "https://api.github.com/users/honglei/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-05-27T16:48:11Z",
            "updated_at": "2014-05-27T16:48:11Z",
            "author_association": "NONE",
            "body": "@danielchatfield \nI find this bug in python bug list:\nhttp://bugs.python.org/issue9291\nits just been closed. when using Python2.7.7rc1, this problem does not happen!\n"
        }
    ]
}