{
    "url": "https://api.github.com/repos/pallets/flask/issues/1680",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1680/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1680/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1680/events",
    "html_url": "https://github.com/pallets/flask/issues/1680",
    "id": 124613351,
    "node_id": "MDU6SXNzdWUxMjQ2MTMzNTE=",
    "number": 1680,
    "title": "Flask isn't doctestable",
    "user": {
        "login": "sils",
        "id": 5716520,
        "node_id": "MDQ6VXNlcjU3MTY1MjA=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5716520?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sils",
        "html_url": "https://github.com/sils",
        "followers_url": "https://api.github.com/users/sils/followers",
        "following_url": "https://api.github.com/users/sils/following{/other_user}",
        "gists_url": "https://api.github.com/users/sils/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sils/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sils/subscriptions",
        "organizations_url": "https://api.github.com/users/sils/orgs",
        "repos_url": "https://api.github.com/users/sils/repos",
        "events_url": "https://api.github.com/users/sils/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sils/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 31,
    "created_at": "2016-01-02T21:57:37Z",
    "updated_at": "2016-05-06T10:09:59Z",
    "closed_at": "2016-04-23T12:20:14Z",
    "author_association": "NONE",
    "body": "```\nlasse@lssteady ~/tmp/pytesttest % cat asd.py \nfrom flask import request\n\ndef addstuff(a,b):\n    \"\"\"\n    Adds stuff:\n\n    >>> addstuff(4,5)\n    9\n\n    See?\n    \"\"\"\n    return a+b\n\nlasse@lssteady ~/tmp/pytesttest % python3   \nPython 3.5.1 (default, Dec  7 2015, 12:58:09) \n[GCC 5.2.0] on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import asd\n>>> import doctest\n>>> doctest.testmod(asd)\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/usr/lib/python3.5/doctest.py\", line 1940, in testmod\n    for test in finder.find(m, name, globs=globs, extraglobs=extraglobs):\n  File \"/usr/lib/python3.5/doctest.py\", line 923, in find\n    self._find(tests, obj, name, module, source_lines, globs, {})\n  File \"/usr/lib/python3.5/doctest.py\", line 982, in _find\n    if ((inspect.isroutine(inspect.unwrap(val))\n  File \"/usr/lib/python3.5/inspect.py\", line 471, in unwrap\n    while _is_wrapper(func):\n  File \"/usr/lib/python3.5/inspect.py\", line 465, in _is_wrapper\n    return hasattr(f, '__wrapped__')\n  File \"/usr/lib/python3.5/site-packages/werkzeug/local.py\", line 343, in __getattr__\n    return getattr(self._get_current_object(), name)\n  File \"/usr/lib/python3.5/site-packages/werkzeug/local.py\", line 302, in _get_current_object\n    return self.__local()\n  File \"/usr/lib/python3.5/site-packages/flask/globals.py\", line 20, in _lookup_req_object\n    raise RuntimeError('working outside of request context')\nRuntimeError: working outside of request context\n>>> \n```\n\nAnyone any idea what happens there? I'd love to doctest my Flask application since it's especially awesome to document endpoints.\n",
    "comments_inline": {}
}