{
    "url": "https://api.github.com/repos/pallets/flask/issues/1694",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1694/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1694/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1694/events",
    "html_url": "https://github.com/pallets/flask/issues/1694",
    "id": 126661428,
    "node_id": "MDU6SXNzdWUxMjY2NjE0Mjg=",
    "number": 1694,
    "title": "Flask.teardown_request always passes an exception on the first request",
    "user": {
        "login": "obskyr",
        "id": 4363779,
        "node_id": "MDQ6VXNlcjQzNjM3Nzk=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/4363779?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/obskyr",
        "html_url": "https://github.com/obskyr",
        "followers_url": "https://api.github.com/users/obskyr/followers",
        "following_url": "https://api.github.com/users/obskyr/following{/other_user}",
        "gists_url": "https://api.github.com/users/obskyr/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/obskyr/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/obskyr/subscriptions",
        "organizations_url": "https://api.github.com/users/obskyr/orgs",
        "repos_url": "https://api.github.com/users/obskyr/repos",
        "events_url": "https://api.github.com/users/obskyr/events{/privacy}",
        "received_events_url": "https://api.github.com/users/obskyr/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 7,
    "created_at": "2016-01-14T14:09:37Z",
    "updated_at": "2016-09-26T17:14:31Z",
    "closed_at": "2016-09-26T17:09:19Z",
    "author_association": "NONE",
    "body": "If a function is set with the `@app.teardown_request` decorator (assuming your Flask instance name is `app`), it _always_ gets passed an exception for the very first request to the server. This exception is a `KeyError` from Werkzeug (even though that particular error is handled in Werkzeug's code).\n\nTry copying and running the following bare-bones flask app:\n\n``` python\n#!/usr/bin/env python\n# -*- coding: utf-8 -*-\n\nfrom flask import Flask\n\nimport sys\nimport traceback\n\napp = Flask(__name__)\n\n@app.teardown_request\ndef teardown_request(exception):\n    if exception:\n        print \"teardown_request received an exception:\"\n        traceback.print_exception(*sys.exc_info())\n    else:\n        print \"Request went through without passing an exception.\"\n\n@app.route(\"/\")\ndef works_but_not_really():\n    return \"This gets returned, so this function finishes.\"\n\nif __name__ == '__main__':\n    app.run('localhost', 5000)\n```\n\nRunning this and performing two GET requests in a row to it results in the following output:\n\n```\n * Running on http://localhost:5000/ (Press CTRL+C to quit)\nteardown_request received an exception:\nTraceback (most recent call last):\n  File \"C:\\Python27\\lib\\site-packages\\werkzeug\\serving.py\", line 647, in inner\n    fd = int(os.environ['WERKZEUG_SERVER_FD'])\n  File \"C:\\Python27\\lib\\os.py\", line 425, in __getitem__\n    return self.data[key.upper()]\nKeyError: 'WERKZEUG_SERVER_FD'\n127.0.0.1 - - [14/Jan/2016 14:57:30] \"GET / HTTP/1.1\" 200 -\nRequest went through without passing an exception.\n127.0.0.1 - - [14/Jan/2016 15:03:32] \"GET / HTTP/1.1\" 200 -\n```\n\nNot only GET requests cause this - at the very least a POST will do the same, and I assume all other types will too. This is a problem in case the teardown request performs a database rollback on receiving an exception - because it means any changes the first request may make to the database are silently (since the page is still returned just fine) ignored.\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/215224668",
            "html_url": "https://github.com/pallets/flask/issues/1694#issuecomment-215224668",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1694",
            "id": 215224668,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIxNTIyNDY2OA==",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-04-27T20:49:26Z",
            "updated_at": "2016-04-27T20:49:26Z",
            "author_association": "MEMBER",
            "body": "I think a better way to fix this would be calling `sys.exc_clear()` at some point to get rid of any unrelated errors. The fact that a caught exception is being passed to `teardown_request` even smells a bit like a bug.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/249561485",
            "html_url": "https://github.com/pallets/flask/issues/1694#issuecomment-249561485",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1694",
            "id": 249561485,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0OTU2MTQ4NQ==",
            "user": {
                "login": "samuzzal",
                "id": 7239294,
                "node_id": "MDQ6VXNlcjcyMzkyOTQ=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/7239294?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/samuzzal",
                "html_url": "https://github.com/samuzzal",
                "followers_url": "https://api.github.com/users/samuzzal/followers",
                "following_url": "https://api.github.com/users/samuzzal/following{/other_user}",
                "gists_url": "https://api.github.com/users/samuzzal/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/samuzzal/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/samuzzal/subscriptions",
                "organizations_url": "https://api.github.com/users/samuzzal/orgs",
                "repos_url": "https://api.github.com/users/samuzzal/repos",
                "events_url": "https://api.github.com/users/samuzzal/events{/privacy}",
                "received_events_url": "https://api.github.com/users/samuzzal/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-26T12:55:28Z",
            "updated_at": "2016-09-26T12:55:28Z",
            "author_association": "NONE",
            "body": "Can anyone please confirm whether this issue is fixed? I could not reproduce this issue with Flask 0.11.1 and Python 2.7 on OS X and Fedora 23. I see that the PR https://github.com/pallets/werkzeug/pull/871 still open though.\n\n#### Steps followed\n- Run @obskyr 's sample code\n\n```\n[sam@localhost ~]$ chmod +x test.py \n[sam@localhost ~]$ ./test.py \n * Running on http://localhost:5000/ (Press CTRL+C to quit)\n```\n- Perform two consecutive GET requests -\n\n```\n[sam@localhost ~]$ curl http://localhost:5000/; curl http://localhost:5000/\n```\n- Response received -\n\n```\n * Running on http://localhost:5000/ (Press CTRL+C to quit)\nRequest went through without passing an exception.\n127.0.0.1 - - [26/Sep/2016 14:22:30] \"GET / HTTP/1.1\" 200 -\nRequest went through without passing an exception.\n127.0.0.1 - - [26/Sep/2016 14:22:30] \"GET / HTTP/1.1\" 200 -\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/249568839",
            "html_url": "https://github.com/pallets/flask/issues/1694#issuecomment-249568839",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1694",
            "id": 249568839,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0OTU2ODgzOQ==",
            "user": {
                "login": "obskyr",
                "id": 4363779,
                "node_id": "MDQ6VXNlcjQzNjM3Nzk=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/4363779?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/obskyr",
                "html_url": "https://github.com/obskyr",
                "followers_url": "https://api.github.com/users/obskyr/followers",
                "following_url": "https://api.github.com/users/obskyr/following{/other_user}",
                "gists_url": "https://api.github.com/users/obskyr/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/obskyr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/obskyr/subscriptions",
                "organizations_url": "https://api.github.com/users/obskyr/orgs",
                "repos_url": "https://api.github.com/users/obskyr/repos",
                "events_url": "https://api.github.com/users/obskyr/events{/privacy}",
                "received_events_url": "https://api.github.com/users/obskyr/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-26T13:26:47Z",
            "updated_at": "2016-09-26T13:26:47Z",
            "author_association": "NONE",
            "body": "Funny you mention it - I ran the test code just yesterday, and got the same result. No more buggy behavior - for me, at least, on flask 0.10.1 + werkzeug 0.10.4. The weird part is I don't think I've updated either since making this issue!\n\nI can't confirm it's fixed, but I _can_ confirm it's not happening for me anymore. Not at the moment, at least. Which is very strange, seeing as it was happening consistently before.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/249574728",
            "html_url": "https://github.com/pallets/flask/issues/1694#issuecomment-249574728",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1694",
            "id": 249574728,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0OTU3NDcyOA==",
            "user": {
                "login": "obskyr",
                "id": 4363779,
                "node_id": "MDQ6VXNlcjQzNjM3Nzk=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/4363779?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/obskyr",
                "html_url": "https://github.com/obskyr",
                "followers_url": "https://api.github.com/users/obskyr/followers",
                "following_url": "https://api.github.com/users/obskyr/following{/other_user}",
                "gists_url": "https://api.github.com/users/obskyr/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/obskyr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/obskyr/subscriptions",
                "organizations_url": "https://api.github.com/users/obskyr/orgs",
                "repos_url": "https://api.github.com/users/obskyr/repos",
                "events_url": "https://api.github.com/users/obskyr/events{/privacy}",
                "received_events_url": "https://api.github.com/users/obskyr/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-26T13:50:10Z",
            "updated_at": "2016-09-26T13:50:22Z",
            "author_association": "NONE",
            "body": "Okay, so here's the low-down. Despite being on Flask 0.10.1 and not having the error occur earlier (something weird was up there, I hope I misremembered something and it's not some sort of weird caching thing) I can now say this:\n\nAfter uninstalling and reinstalling a lot of permutations of Flask and Werkzeug, this is my conclusion: the error **occurs on Flask 0.10.1 even with the newest version of Werkzeug**. However, **as of Flask 0.11.0 the error does not occur anymore**, regardless of Werkzeug version. My tests haven't been super scientific, but this is the conclusion I've arrived at.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/249622516",
            "html_url": "https://github.com/pallets/flask/issues/1694#issuecomment-249622516",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1694",
            "id": 249622516,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0OTYyMjUxNg==",
            "user": {
                "login": "samuzzal",
                "id": 7239294,
                "node_id": "MDQ6VXNlcjcyMzkyOTQ=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/7239294?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/samuzzal",
                "html_url": "https://github.com/samuzzal",
                "followers_url": "https://api.github.com/users/samuzzal/followers",
                "following_url": "https://api.github.com/users/samuzzal/following{/other_user}",
                "gists_url": "https://api.github.com/users/samuzzal/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/samuzzal/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/samuzzal/subscriptions",
                "organizations_url": "https://api.github.com/users/samuzzal/orgs",
                "repos_url": "https://api.github.com/users/samuzzal/repos",
                "events_url": "https://api.github.com/users/samuzzal/events{/privacy}",
                "received_events_url": "https://api.github.com/users/samuzzal/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-26T16:30:43Z",
            "updated_at": "2016-09-26T16:30:43Z",
            "author_association": "NONE",
            "body": "I got that exception now with Flask (0.10.1) and Werkzeug (0.11.11).\n\nI am wondering whether or not to try out any fix for this. Especially when the issue is not reproducible with Flask 0.11.1 and it is only the first request that fails with 0.10.0.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/249633051",
            "html_url": "https://github.com/pallets/flask/issues/1694#issuecomment-249633051",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1694",
            "id": 249633051,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0OTYzMzA1MQ==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-26T17:09:19Z",
            "updated_at": "2016-09-26T17:09:19Z",
            "author_association": "MEMBER",
            "body": "This is fixed in 0.11, most likely by #1393\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/249634460",
            "html_url": "https://github.com/pallets/flask/issues/1694#issuecomment-249634460",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1694",
            "id": 249634460,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0OTYzNDQ2MA==",
            "user": {
                "login": "obskyr",
                "id": 4363779,
                "node_id": "MDQ6VXNlcjQzNjM3Nzk=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/4363779?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/obskyr",
                "html_url": "https://github.com/obskyr",
                "followers_url": "https://api.github.com/users/obskyr/followers",
                "following_url": "https://api.github.com/users/obskyr/following{/other_user}",
                "gists_url": "https://api.github.com/users/obskyr/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/obskyr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/obskyr/subscriptions",
                "organizations_url": "https://api.github.com/users/obskyr/orgs",
                "repos_url": "https://api.github.com/users/obskyr/repos",
                "events_url": "https://api.github.com/users/obskyr/events{/privacy}",
                "received_events_url": "https://api.github.com/users/obskyr/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-26T17:14:30Z",
            "updated_at": "2016-09-26T17:14:30Z",
            "author_association": "NONE",
            "body": "Ah, fantastic. Thanks for clearing that up. Incidentally that was one of the few things that stopped me from fully recommending Flask to people - after all, you shouldn't have to mess with weird workarounds to do basic stuff. All good now!\n"
        }
    ]
}