{
    "url": "https://api.github.com/repos/pallets/flask/issues/2162",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2162/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2162/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2162/events",
    "html_url": "https://github.com/pallets/flask/issues/2162",
    "id": 203840715,
    "node_id": "MDU6SXNzdWUyMDM4NDA3MTU=",
    "number": 2162,
    "title": "GAE not displaying error messages for 0.12",
    "user": {
        "login": "jalexvig",
        "id": 12684689,
        "node_id": "MDQ6VXNlcjEyNjg0Njg5",
        "avatar_url": "https://avatars1.githubusercontent.com/u/12684689?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jalexvig",
        "html_url": "https://github.com/jalexvig",
        "followers_url": "https://api.github.com/users/jalexvig/followers",
        "following_url": "https://api.github.com/users/jalexvig/following{/other_user}",
        "gists_url": "https://api.github.com/users/jalexvig/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jalexvig/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jalexvig/subscriptions",
        "organizations_url": "https://api.github.com/users/jalexvig/orgs",
        "repos_url": "https://api.github.com/users/jalexvig/repos",
        "events_url": "https://api.github.com/users/jalexvig/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jalexvig/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2017-01-29T00:05:15Z",
    "updated_at": "2017-05-23T06:40:58Z",
    "closed_at": "2017-05-22T23:20:07Z",
    "author_association": "NONE",
    "body": "When I use Flask 0.12 in my Google App Engine project I get no error messages. So a function that might throw an error would result in a log like:\r\n\r\n```\r\nINFO     2017-01-29 00:03:05,820 sdk_update_checker.py:229] Checking for updates to the SDK.\r\nINFO     2017-01-29 00:03:06,428 api_server.py:205] Starting API server at: http://localhost:54929\r\nINFO     2017-01-29 00:03:06,432 dispatcher.py:197] Starting module \"default\" running at: http://127.0.0.1:8080\r\nINFO     2017-01-29 00:03:06,434 admin_server.py:116] Starting admin server at: http://localhost:8000\r\nINFO     2017-01-29 00:03:10,212 module.py:787] default: \"GET / HTTP/1.1\" 500 291\r\nINFO     2017-01-29 00:03:11,711 module.py:787] default: \"GET /favicon.ico HTTP/1.1\" 404 233\r\n```\r\n\r\nwhereas when I downgrade to Flask 0.11.1 I actually get the error messaging I've come to know and love:\r\n\r\n```\r\nINFO     2017-01-28 23:58:06,986 sdk_update_checker.py:229] Checking for updates to the SDK.\r\nINFO     2017-01-28 23:58:07,234 api_server.py:205] Starting API server at: http://localhost:54720\r\nINFO     2017-01-28 23:58:07,238 dispatcher.py:197] Starting module \"default\" running at: http://127.0.0.1:8080\r\nINFO     2017-01-28 23:58:07,240 admin_server.py:116] Starting admin server at: http://localhost:8000\r\nERROR    2017-01-28 23:58:11,804 app.py:1587] Exception on / [GET]\r\nTraceback (most recent call last):\r\n  File \"/Users/alex/yphh/petition_companies/lib/flask/app.py\", line 1988, in wsgi_app\r\n    response = self.full_dispatch_request()\r\n  File \"/Users/alex/yphh/petition_companies/lib/flask/app.py\", line 1641, in full_dispatch_request\r\n    rv = self.handle_user_exception(e)\r\n  File \"/Users/alex/yphh/petition_companies/lib/flask/app.py\", line 1544, in handle_user_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"/Users/alex/yphh/petition_companies/lib/flask/app.py\", line 1639, in full_dispatch_request\r\n    rv = self.dispatch_request()\r\n  File \"/Users/alex/yphh/petition_companies/lib/flask/app.py\", line 1625, in dispatch_request\r\n    return self.view_functions[rule.endpoint](**req.view_args)\r\n  File \"/Users/alex/yphh/petition_companies/main.py\", line 70, in index\r\n    1 / 0\r\nZeroDivisionError: integer division or modulo by zero\r\nINFO     2017-01-28 23:58:11,821 module.py:787] default: \"GET / HTTP/1.1\" 500 291\r\nINFO     2017-01-28 23:58:13,100 module.py:787] default: \"GET /favicon.ico HTTP/1.1\" 404 233\r\n```\r\n\r\nAside from the traceback the two are the same.",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/303245834",
            "html_url": "https://github.com/pallets/flask/issues/2162#issuecomment-303245834",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2162",
            "id": 303245834,
            "node_id": "MDEyOklzc3VlQ29tbWVudDMwMzI0NTgzNA==",
            "user": {
                "login": "brianrusso",
                "id": 6276108,
                "node_id": "MDQ6VXNlcjYyNzYxMDg=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/6276108?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/brianrusso",
                "html_url": "https://github.com/brianrusso",
                "followers_url": "https://api.github.com/users/brianrusso/followers",
                "following_url": "https://api.github.com/users/brianrusso/following{/other_user}",
                "gists_url": "https://api.github.com/users/brianrusso/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/brianrusso/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/brianrusso/subscriptions",
                "organizations_url": "https://api.github.com/users/brianrusso/orgs",
                "repos_url": "https://api.github.com/users/brianrusso/repos",
                "events_url": "https://api.github.com/users/brianrusso/events{/privacy}",
                "received_events_url": "https://api.github.com/users/brianrusso/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2017-05-22T23:18:40Z",
            "updated_at": "2017-05-22T23:19:16Z",
            "author_association": "NONE",
            "body": "Cannot replicate on GAE with flask 0.12.1\r\n/fail endpoint does a divide by zero and the stacktrace correctly shows up when using the gcloud log command.\r\n\r\n```\r\n2017-05-22 23:16:19 default[20170522t155304]  \"GET /\" 200\r\n2017-05-22 23:16:51 default[20170522t160846]  [2017-05-22 23:16:51,079] ERROR in app: Exception on /fail [GET]\r\n2017-05-22 23:16:51 default[20170522t160846]  Traceback (most recent call last):    File \"/env/lib/python3.5/site-packages/flask/app.py\", line 1982, in wsgi_app      response = self.full_dispatch_request()    File \"/env/lib/python3.5/s\r\nite-packages/flask/app.py\", line 1614, in full_dispatch_request      rv = self.handle_user_exception(e)    File \"/env/lib/python3.5/site-packages/flask/app.py\", line 1517, in handle_user_exception      reraise(exc_type, exc_value, tb) \r\n   File \"/env/lib/python3.5/site-packages/flask/_compat.py\", line 33, in reraise      raise value    File \"/env/lib/python3.5/site-packages/flask/app.py\", line 1612, in full_dispatch_request      rv = self.dispatch_request()    File \"/\r\nenv/lib/python3.5/site-packages/flask/app.py\", line 1598, in dispatch_request      return self.view_functions[rule.endpoint](**req.view_args)    File \"/home/vmagent/app/main.py\", line 31, in fail      return str(3/0)  ZeroDivisionError\r\n: division by zero\r\n2017-05-22 23:16:51 default[20170522t160846]  ERROR:root:An error occurred during a request.\r\n```"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/303304743",
            "html_url": "https://github.com/pallets/flask/issues/2162#issuecomment-303304743",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2162",
            "id": 303304743,
            "node_id": "MDEyOklzc3VlQ29tbWVudDMwMzMwNDc0Mw==",
            "user": {
                "login": "jeffwidman",
                "id": 483314,
                "node_id": "MDQ6VXNlcjQ4MzMxNA==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/483314?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/jeffwidman",
                "html_url": "https://github.com/jeffwidman",
                "followers_url": "https://api.github.com/users/jeffwidman/followers",
                "following_url": "https://api.github.com/users/jeffwidman/following{/other_user}",
                "gists_url": "https://api.github.com/users/jeffwidman/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/jeffwidman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jeffwidman/subscriptions",
                "organizations_url": "https://api.github.com/users/jeffwidman/orgs",
                "repos_url": "https://api.github.com/users/jeffwidman/repos",
                "events_url": "https://api.github.com/users/jeffwidman/events{/privacy}",
                "received_events_url": "https://api.github.com/users/jeffwidman/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2017-05-23T06:40:58Z",
            "updated_at": "2017-05-23T06:40:58Z",
            "author_association": "MEMBER",
            "body": "@brianrusso Just wanted to say thanks for your hard work on testing whether all these old tickets are still valid. Really, really appreciated."
        }
    ]
}