{
    "url": "https://api.github.com/repos/pallets/flask/issues/2216",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2216/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2216/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2216/events",
    "html_url": "https://github.com/pallets/flask/issues/2216",
    "id": 215503250,
    "node_id": "MDU6SXNzdWUyMTU1MDMyNTA=",
    "number": 2216,
    "title": "EOFError during GET request due to broken session file.",
    "user": {
        "login": "Nexolight",
        "id": 7711052,
        "node_id": "MDQ6VXNlcjc3MTEwNTI=",
        "avatar_url": "https://avatars3.githubusercontent.com/u/7711052?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Nexolight",
        "html_url": "https://github.com/Nexolight",
        "followers_url": "https://api.github.com/users/Nexolight/followers",
        "following_url": "https://api.github.com/users/Nexolight/following{/other_user}",
        "gists_url": "https://api.github.com/users/Nexolight/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Nexolight/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Nexolight/subscriptions",
        "organizations_url": "https://api.github.com/users/Nexolight/orgs",
        "repos_url": "https://api.github.com/users/Nexolight/repos",
        "events_url": "https://api.github.com/users/Nexolight/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Nexolight/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2017-03-20T17:51:43Z",
    "updated_at": "2017-05-24T00:23:06Z",
    "closed_at": "2017-05-24T00:23:06Z",
    "author_association": "NONE",
    "body": "I get this error in my logs from time to time and the only solution is to restart the server. I have no idea from where it comes but I assume this is a flask internal issue.\r\n\r\n```\r\n2017-03-20 18:42:17,346 ERROR    xposed.xposed_main                            Exception on /serverstats [GET]\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.4/dist-packages/flask/app.py\", line 1817, in wsgi_app\r\n    response = self.full_dispatch_request()\r\n  File \"/usr/local/lib/python3.4/dist-packages/flask/app.py\", line 1479, in full_dispatch_request\r\n    response = self.process_response(response)\r\n  File \"/usr/local/lib/python3.4/dist-packages/flask/app.py\", line 1693, in process_response\r\n    self.save_session(ctx.session, response)\r\n  File \"/usr/local/lib/python3.4/dist-packages/flask/app.py\", line 837, in save_session\r\n    return self.session_interface.save_session(self, session, response)\r\n  File \"/usr/local/lib/python3.4/dist-packages/flask_session/sessions.py\", line 355, in save_session\r\n    total_seconds(app.permanent_session_lifetime))\r\n  File \"/usr/local/lib/python3.4/dist-packages/werkzeug/contrib/cache.py\", line 762, in set\r\n    self._prune()\r\n  File \"/usr/local/lib/python3.4/dist-packages/werkzeug/contrib/cache.py\", line 715, in _prune\r\n    expires = pickle.load(f)\r\nEOFError: Ran out of input\r\n\r\n```",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/287845630",
            "html_url": "https://github.com/pallets/flask/issues/2216#issuecomment-287845630",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2216",
            "id": 287845630,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI4Nzg0NTYzMA==",
            "user": {
                "login": "Nexolight",
                "id": 7711052,
                "node_id": "MDQ6VXNlcjc3MTEwNTI=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/7711052?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Nexolight",
                "html_url": "https://github.com/Nexolight",
                "followers_url": "https://api.github.com/users/Nexolight/followers",
                "following_url": "https://api.github.com/users/Nexolight/following{/other_user}",
                "gists_url": "https://api.github.com/users/Nexolight/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Nexolight/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Nexolight/subscriptions",
                "organizations_url": "https://api.github.com/users/Nexolight/orgs",
                "repos_url": "https://api.github.com/users/Nexolight/repos",
                "events_url": "https://api.github.com/users/Nexolight/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Nexolight/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2017-03-20T18:00:23Z",
            "updated_at": "2017-03-20T18:00:23Z",
            "author_association": "NONE",
            "body": "Deleting the session files does help.\r\nThe server does restart from time to time and might terminate the process what probably could lead to those EOFErrors.\r\n\r\nAnyway flask should handle this error by just deleting the session. It's not a big deal, doesn't happen often."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/287869298",
            "html_url": "https://github.com/pallets/flask/issues/2216#issuecomment-287869298",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2216",
            "id": 287869298,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI4Nzg2OTI5OA==",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2017-03-20T19:21:04Z",
            "updated_at": "2017-03-20T19:21:32Z",
            "author_association": "MEMBER",
            "body": "`flask_session` is a third-party extension and not part of Flask. So it's either a bug in there or in werkzeug's cache layer."
        }
    ]
}