{
    "url": "https://api.github.com/repos/pallets/flask/issues/223",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/223/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/223/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/223/events",
    "html_url": "https://github.com/pallets/flask/issues/223",
    "id": 791360,
    "node_id": "MDU6SXNzdWU3OTEzNjA=",
    "number": 223,
    "title": "sys.excepthook error",
    "user": {
        "login": "ghost",
        "id": 10137,
        "node_id": "MDQ6VXNlcjEwMTM3",
        "avatar_url": "https://avatars3.githubusercontent.com/u/10137?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ghost",
        "html_url": "https://github.com/ghost",
        "followers_url": "https://api.github.com/users/ghost/followers",
        "following_url": "https://api.github.com/users/ghost/following{/other_user}",
        "gists_url": "https://api.github.com/users/ghost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ghost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
        "organizations_url": "https://api.github.com/users/ghost/orgs",
        "repos_url": "https://api.github.com/users/ghost/repos",
        "events_url": "https://api.github.com/users/ghost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ghost/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 9,
    "created_at": "2011-04-19T23:37:32Z",
    "updated_at": "2013-10-29T11:50:00Z",
    "closed_at": "2011-06-24T14:36:37Z",
    "author_association": "NONE",
    "body": "When restarting in debug mode, this error was output:\n- Detected change in 'atest.py', reloading\n  Unhandled exception in thread started by\n  sys.excepthook is missing\n  lost sys.stderr\n- Restarting with reloader...\n\nIt may be related to a known issue calling sys.excepthook from threads, see http://bugs.python.org/issue1230540\n\nUsing Flask 0.6.1, Werkzeug 0.62 under Python 2.7 64-bit on Solaris10/SPARC.\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/1052991",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-1052991",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 1052991,
            "node_id": "MDEyOklzc3VlQ29tbWVudDEwNTI5OTE=",
            "user": {
                "login": "mitsuhiko",
                "id": 7396,
                "node_id": "MDQ6VXNlcjczOTY=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/7396?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mitsuhiko",
                "html_url": "https://github.com/mitsuhiko",
                "followers_url": "https://api.github.com/users/mitsuhiko/followers",
                "following_url": "https://api.github.com/users/mitsuhiko/following{/other_user}",
                "gists_url": "https://api.github.com/users/mitsuhiko/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mitsuhiko/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mitsuhiko/subscriptions",
                "organizations_url": "https://api.github.com/users/mitsuhiko/orgs",
                "repos_url": "https://api.github.com/users/mitsuhiko/repos",
                "events_url": "https://api.github.com/users/mitsuhiko/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mitsuhiko/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2011-04-25T14:05:59Z",
            "updated_at": "2011-04-25T14:05:59Z",
            "author_association": "MEMBER",
            "body": "Not sure how I could reproduce that as I don't have access to a solaris machine :(\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/1055569",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-1055569",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 1055569,
            "node_id": "MDEyOklzc3VlQ29tbWVudDEwNTU1Njk=",
            "user": {
                "login": "ghost",
                "id": 10137,
                "node_id": "MDQ6VXNlcjEwMTM3",
                "avatar_url": "https://avatars3.githubusercontent.com/u/10137?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ghost",
                "html_url": "https://github.com/ghost",
                "followers_url": "https://api.github.com/users/ghost/followers",
                "following_url": "https://api.github.com/users/ghost/following{/other_user}",
                "gists_url": "https://api.github.com/users/ghost/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ghost/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
                "organizations_url": "https://api.github.com/users/ghost/orgs",
                "repos_url": "https://api.github.com/users/ghost/repos",
                "events_url": "https://api.github.com/users/ghost/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ghost/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2011-04-25T22:39:01Z",
            "updated_at": "2011-04-25T22:39:01Z",
            "author_association": "NONE",
            "body": "I have not been able to reproduce it yet either - it only happened after\nrunning the server in debug mode overnight, then having it automatically\nrestart upon a file change the next morning. I just thought maybe the\nknowledge around this known issue in general might be some use in tracking\ndown the problem.\n\nOn Tue, Apr 26, 2011 at 12:06 AM, mitsuhiko <\nreply@reply.github.com>wrote:\n\n> Not sure how I could reproduce that as I don't have access to a solaris\n> machine :(\n> \n> ## \n> \n> Reply to this email directly or view it on GitHub:\n> https://github.com/mitsuhiko/flask/issues/223#comment_1052991\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/1432696",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-1432696",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 1432696,
            "node_id": "MDEyOklzc3VlQ29tbWVudDE0MzI2OTY=",
            "user": {
                "login": "mitsuhiko",
                "id": 7396,
                "node_id": "MDQ6VXNlcjczOTY=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/7396?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mitsuhiko",
                "html_url": "https://github.com/mitsuhiko",
                "followers_url": "https://api.github.com/users/mitsuhiko/followers",
                "following_url": "https://api.github.com/users/mitsuhiko/following{/other_user}",
                "gists_url": "https://api.github.com/users/mitsuhiko/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mitsuhiko/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mitsuhiko/subscriptions",
                "organizations_url": "https://api.github.com/users/mitsuhiko/orgs",
                "repos_url": "https://api.github.com/users/mitsuhiko/repos",
                "events_url": "https://api.github.com/users/mitsuhiko/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mitsuhiko/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2011-06-24T14:36:37Z",
            "updated_at": "2011-06-24T14:36:37Z",
            "author_association": "MEMBER",
            "body": "I close this for the time being. Nobody else mentioned it and I cannot reproduce.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/22595696",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-22595696",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 22595696,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIyNTk1Njk2",
            "user": {
                "login": "Bleyddyn",
                "id": 4088291,
                "node_id": "MDQ6VXNlcjQwODgyOTE=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/4088291?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Bleyddyn",
                "html_url": "https://github.com/Bleyddyn",
                "followers_url": "https://api.github.com/users/Bleyddyn/followers",
                "following_url": "https://api.github.com/users/Bleyddyn/following{/other_user}",
                "gists_url": "https://api.github.com/users/Bleyddyn/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Bleyddyn/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Bleyddyn/subscriptions",
                "organizations_url": "https://api.github.com/users/Bleyddyn/orgs",
                "repos_url": "https://api.github.com/users/Bleyddyn/repos",
                "events_url": "https://api.github.com/users/Bleyddyn/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Bleyddyn/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-08-13T20:39:47Z",
            "updated_at": "2013-08-13T20:39:47Z",
            "author_association": "NONE",
            "body": "Two years, old, I know, but I'm seeing the same error when running Flask on a Raspberry Pi, running Raspbian. It happens after I Ctrl-C to kill the server.\n\n$ python hello-template.py \n- Running on http://0.0.0.0:8088/\n- Restarting with reloader\n  192.168.0.102 - - [13/Aug/2013 13:32:49] \"GET / HTTP/1.1\" 200 -\n  192.168.0.102 - - [13/Aug/2013 13:32:54] \"GET /favicon.ico HTTP/1.1\" 404 -\n  $ Unhandled exception in thread started by \n  sys.excepthook is missing\n  lost sys.stderr\n\n$ python --version\nPython 2.7.3\n\nFlask version is: **version** = '0.10.1'\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/23840949",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-23840949",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 23840949,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzODQwOTQ5",
            "user": {
                "login": "sethreidnz",
                "id": 4713713,
                "node_id": "MDQ6VXNlcjQ3MTM3MTM=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/4713713?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/sethreidnz",
                "html_url": "https://github.com/sethreidnz",
                "followers_url": "https://api.github.com/users/sethreidnz/followers",
                "following_url": "https://api.github.com/users/sethreidnz/following{/other_user}",
                "gists_url": "https://api.github.com/users/sethreidnz/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/sethreidnz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sethreidnz/subscriptions",
                "organizations_url": "https://api.github.com/users/sethreidnz/orgs",
                "repos_url": "https://api.github.com/users/sethreidnz/repos",
                "events_url": "https://api.github.com/users/sethreidnz/events{/privacy}",
                "received_events_url": "https://api.github.com/users/sethreidnz/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-09-05T02:58:16Z",
            "updated_at": "2013-09-05T02:58:16Z",
            "author_association": "NONE",
            "body": "I too am also having the exact problem. On the raspberry Pi running Debian. But the application works fine if you don't stop it. I don't know the implications of this as I have only just started using flask. But I am simply echo-ing Bleyddyn's claim that it is still happening.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/23860568",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-23860568",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 23860568,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzODYwNTY4",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-09-05T11:16:01Z",
            "updated_at": "2013-09-05T11:16:01Z",
            "author_association": "MEMBER",
            "body": "I guess this issue only exists with the builtin server and not with something like gunicorn?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/23874422",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-23874422",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 23874422,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzODc0NDIy",
            "user": {
                "login": "ghost",
                "id": 10137,
                "node_id": "MDQ6VXNlcjEwMTM3",
                "avatar_url": "https://avatars3.githubusercontent.com/u/10137?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ghost",
                "html_url": "https://github.com/ghost",
                "followers_url": "https://api.github.com/users/ghost/followers",
                "following_url": "https://api.github.com/users/ghost/following{/other_user}",
                "gists_url": "https://api.github.com/users/ghost/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ghost/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
                "organizations_url": "https://api.github.com/users/ghost/orgs",
                "repos_url": "https://api.github.com/users/ghost/repos",
                "events_url": "https://api.github.com/users/ghost/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ghost/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-09-05T15:05:20Z",
            "updated_at": "2013-09-05T15:05:20Z",
            "author_association": "NONE",
            "body": "@untitaker I think so. The only threading-related method used in Werkzeug is `thread.start_new_thread` in `run_with_reloader`@[werkzeug/serving.py](https://github.com/mitsuhiko/werkzeug/blob/6e5591c410db70a6da5a5a35fcc9e61da72d11fd/werkzeug/serving.py#L611) - and maybe we should use `threading.Thread` instead (see http://stackoverflow.com/questions/9532264/how-to-use-multiple-thread-in-python).\n@Bleyddyn Can you confirm my supposition by disabling reloading (see \"Keep in mind\" in [Flask docs for `Flask.run`](http://flask.pocoo.org/docs/api/)) and see if it works?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/23890651",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-23890651",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 23890651,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzODkwNjUx",
            "user": {
                "login": "Bleyddyn",
                "id": 4088291,
                "node_id": "MDQ6VXNlcjQwODgyOTE=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/4088291?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Bleyddyn",
                "html_url": "https://github.com/Bleyddyn",
                "followers_url": "https://api.github.com/users/Bleyddyn/followers",
                "following_url": "https://api.github.com/users/Bleyddyn/following{/other_user}",
                "gists_url": "https://api.github.com/users/Bleyddyn/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Bleyddyn/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Bleyddyn/subscriptions",
                "organizations_url": "https://api.github.com/users/Bleyddyn/orgs",
                "repos_url": "https://api.github.com/users/Bleyddyn/repos",
                "events_url": "https://api.github.com/users/Bleyddyn/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Bleyddyn/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-09-05T18:27:45Z",
            "updated_at": "2013-09-05T18:31:28Z",
            "author_association": "NONE",
            "body": "@gioi Confirmed:\n\n```\n$ python hello-template.py \n * Running on http://0.0.0.0:8088/\n * Restarting with reloader\n^CUnhandled exception in thread started by \nsys.excepthook is missing\nlost sys.stderr\n$ vi hello-template.py  # Here I added use_reloader=False to the run call\n$ python hello-template.py \n * Running on http://0.0.0.0:8088/\n^C\n$\n```\n\nAs an aside I've been running Flask under Apache on my Pi for a while now with no issues. Made it very easy for me to replace some PHP code! \n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/23903506",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-23903506",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 23903506,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTAzNTA2",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-09-05T21:34:02Z",
            "updated_at": "2013-09-05T21:34:28Z",
            "author_association": "MEMBER",
            "body": "Can you confirm this patch works?\n\n``` diff\ndiff --git a/werkzeug/serving.py b/werkzeug/serving.py\nindex 2fb8660..8d6a116 100644\n--- a/werkzeug/serving.py\n+++ b/werkzeug/serving.py\n@@ -49,6 +49,8 @@ try:\n except ImportError:\n     import _thread as thread\n\n+import threading\n+\n try:\n     from SocketServer import ThreadingMixIn, ForkingMixIn\n     from BaseHTTPServer import HTTPServer, BaseHTTPRequestHandler\n@@ -608,7 +610,8 @@ def run_with_reloader(main_func, extra_files=None, interval=1):\n     import signal\n     signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))\n     if os.environ.get('WERKZEUG_RUN_MAIN') == 'true':\n-        thread.start_new_thread(main_func, ())\n+        thread = threading.Thread(target=main_func)\n+        thread.start()\n         try:\n             reloader_loop(extra_files, interval)\n         except KeyboardInterrupt:\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/23903836",
            "html_url": "https://github.com/pallets/flask/issues/223#issuecomment-23903836",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/223",
            "id": 23903836,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTAzODM2",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-09-05T21:39:22Z",
            "updated_at": "2013-09-05T21:39:22Z",
            "author_association": "MEMBER",
            "body": "Or try the branch https://github.com/untitaker/werkzeug/tree/issue223\n"
        }
    ]
}