{
    "url": "https://api.github.com/repos/pallets/flask/issues/2517",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2517/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2517/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2517/events",
    "html_url": "https://github.com/pallets/flask/issues/2517",
    "id": 272917860,
    "node_id": "MDU6SXNzdWUyNzI5MTc4NjA=",
    "number": 2517,
    "title": "Exception while opening session causes auto_pop not to be executed on the context",
    "user": {
        "login": "ottonello",
        "id": 5169552,
        "node_id": "MDQ6VXNlcjUxNjk1NTI=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/5169552?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ottonello",
        "html_url": "https://github.com/ottonello",
        "followers_url": "https://api.github.com/users/ottonello/followers",
        "following_url": "https://api.github.com/users/ottonello/following{/other_user}",
        "gists_url": "https://api.github.com/users/ottonello/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ottonello/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ottonello/subscriptions",
        "organizations_url": "https://api.github.com/users/ottonello/orgs",
        "repos_url": "https://api.github.com/users/ottonello/repos",
        "events_url": "https://api.github.com/users/ottonello/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ottonello/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": {
        "url": "https://api.github.com/repos/pallets/flask/milestones/2",
        "html_url": "https://github.com/pallets/flask/milestone/2",
        "labels_url": "https://api.github.com/repos/pallets/flask/milestones/2/labels",
        "id": 795954,
        "node_id": "MDk6TWlsZXN0b25lNzk1OTU0",
        "number": 2,
        "title": "1.0",
        "description": "",
        "creator": {
            "login": "untitaker",
            "id": 837573,
            "node_id": "MDQ6VXNlcjgzNzU3Mw==",
            "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/untitaker",
            "html_url": "https://github.com/untitaker",
            "followers_url": "https://api.github.com/users/untitaker/followers",
            "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
            "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
            "organizations_url": "https://api.github.com/users/untitaker/orgs",
            "repos_url": "https://api.github.com/users/untitaker/repos",
            "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
            "received_events_url": "https://api.github.com/users/untitaker/received_events",
            "type": "User",
            "site_admin": false
        },
        "open_issues": 0,
        "closed_issues": 159,
        "state": "closed",
        "created_at": "2014-09-19T15:47:20Z",
        "updated_at": "2018-04-26T21:07:44Z",
        "due_on": "2018-04-26T07:00:00Z",
        "closed_at": "2018-04-26T21:07:44Z"
    },
    "comments": 2,
    "created_at": "2017-11-10T12:31:10Z",
    "updated_at": "2018-01-04T21:12:32Z",
    "closed_at": "2018-01-04T21:12:16Z",
    "author_association": "NONE",
    "body": "### Expected Behavior\r\n\r\nauto_pop of the request context should be executed regardless of whether an exception happened after pushing the context(for example, when opening a session).\r\n\r\nWe're using Redis sessions from flask_session:\r\n```python\r\ndef _setup_session(app):\r\n    from util.cache.region import cache_region\r\n    from dogpile.cache.backends.null import NullBackend\r\n    from flask_session import RedisSessionInterface\r\n\r\n    if not isinstance(cache_region.backend, NullBackend):\r\n        redis = cache_region.backend.client\r\n        session_interface = RedisSessionInterface(redis, 'test.session.', use_signer=False, permanent=False)\r\n        app.session_interface = session_interface\r\n```\r\n\r\n### Actual Behavior\r\n\r\nThe request context is not popped whenever there is a timeout getting the session from Redis. \r\nWe can see in following requests the 'g' object still holds information from the failing request.\r\n\r\nIn ctx.py the context is first pushed and then the session is opened:\r\n```pytb\r\n        _request_ctx_stack.push(self)\r\n\r\n        # Open the session at the moment that the request context is\r\n        # available. This allows a custom open_session method to use the\r\n        # request context (e.g. code that access database information\r\n        # stored on `g` instead of the appcontext).\r\n        self.session = self.app.open_session(self.request)\r\n```\r\n\r\nBut if open_session() fails, then ctx.auto_pop() is not executed. Perhaps ctx.push() should also be under the try...finally block in app.py?\r\n\r\nThis is the exception that triggers the context not to be popped:\r\n```pytb\r\nredis.exceptions:TimeoutError: Timeout reading from socket\r\nTraceback (most recent call last):\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/newrelic-2.74.0.54/newrelic/api/web_transaction.py\", line 738, in __iter__\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/newrelic-2.74.0.54/newrelic/api/web_transaction.py\", line 1114, in __call__\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/werkzeug/contrib/fixers.py\", line 152, in __call__\r\nFile \"/var/www/censored_production/www/censored/util/logging.py\", line 136, in __call__\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/flask/app.py\", line 1813, in wsgi_app\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/flask/ctx.py\", line 321, in push\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/flask/app.py\", line 825, in open_session\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/flask_session/sessions.py\", line 132, in open_session\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/newrelic-2.74.0.54/newrelic/hooks/datastore_redis.py\", line 67, in _nr_wrapper_Redis_method_\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/redis/client.py\", line 880, in get\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/redis/client.py\", line 573, in execute_command\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/redis/client.py\", line 585, in parse_response\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/redis/connection.py\", line 577, in read_response\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/redis/connection.py\", line 238, in read_response\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/redis/connection.py\", line 168, in readline\r\nFile \"/var/www/censored_production/env/lib/python2.7/site-packages/redis/connection.py\", line 139, in _read_from_socket\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 2.7.6\r\n* Flask version: 0.10.1\r\n* Werkzeug version: 0.11.11\r\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/344210031",
            "html_url": "https://github.com/pallets/flask/issues/2517#issuecomment-344210031",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2517",
            "id": 344210031,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM0NDIxMDAzMQ==",
            "user": {
                "login": "ottonello",
                "id": 5169552,
                "node_id": "MDQ6VXNlcjUxNjk1NTI=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/5169552?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ottonello",
                "html_url": "https://github.com/ottonello",
                "followers_url": "https://api.github.com/users/ottonello/followers",
                "following_url": "https://api.github.com/users/ottonello/following{/other_user}",
                "gists_url": "https://api.github.com/users/ottonello/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ottonello/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ottonello/subscriptions",
                "organizations_url": "https://api.github.com/users/ottonello/orgs",
                "repos_url": "https://api.github.com/users/ottonello/repos",
                "events_url": "https://api.github.com/users/ottonello/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ottonello/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2017-11-14T10:14:01Z",
            "updated_at": "2017-11-14T10:14:01Z",
            "author_association": "NONE",
            "body": "Does anybody agree? Notice this specific issue can also be fixed by catching the timeout in flask_session but I still think Flask should handle this gracefully and clean up the context."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/355399958",
            "html_url": "https://github.com/pallets/flask/issues/2517#issuecomment-355399958",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2517",
            "id": 355399958,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM1NTM5OTk1OA==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-01-04T21:12:16Z",
            "updated_at": "2018-01-04T21:12:16Z",
            "author_association": "MEMBER",
            "body": "Duplicate of #1528, fixed in #2254. This will be in the next release."
        }
    ]
}