{
    "url": "https://api.github.com/repos/pallets/flask/issues/2706",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2706/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2706/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2706/events",
    "html_url": "https://github.com/pallets/flask/issues/2706",
    "id": 315511857,
    "node_id": "MDU6SXNzdWUzMTU1MTE4NTc=",
    "number": 2706,
    "title": "Different app discovery behavior on commands run and shell ",
    "user": {
        "login": "rochacbruno",
        "id": 458654,
        "node_id": "MDQ6VXNlcjQ1ODY1NA==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/458654?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rochacbruno",
        "html_url": "https://github.com/rochacbruno",
        "followers_url": "https://api.github.com/users/rochacbruno/followers",
        "following_url": "https://api.github.com/users/rochacbruno/following{/other_user}",
        "gists_url": "https://api.github.com/users/rochacbruno/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rochacbruno/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rochacbruno/subscriptions",
        "organizations_url": "https://api.github.com/users/rochacbruno/orgs",
        "repos_url": "https://api.github.com/users/rochacbruno/repos",
        "events_url": "https://api.github.com/users/rochacbruno/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rochacbruno/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 7,
    "created_at": "2018-04-18T14:45:01Z",
    "updated_at": "2018-04-18T15:24:43Z",
    "closed_at": "2018-04-18T15:00:28Z",
    "author_association": "CONTRIBUTOR",
    "body": "The commands `run` and `shell` are behaving differently to locate the `app`, I can send a PR but first I want to confirm if this is a problem or expected behavior.\r\n\r\n### Expected Behavior\r\n\r\nAssuming the tree\r\n\r\n```bash\r\n/topdir\r\n|____/appdir\r\n|_________/app.py \r\n```\r\nthen\r\n\r\n```bash\r\nexport FLASK_APP=app.py\r\ncd topdir\r\n```\r\n\r\nIf you run\r\n\r\n```bash\r\nflask run\r\n```\r\n\r\nThe command can find the `app` in the subfolder and run successfully\r\n\r\nExpected the same to happen for `shell` \r\n\r\n```bash\r\ncd topdir\r\nflask shell\r\n>>> \r\n```\r\n\r\n### Actual Behavior\r\n\r\n\r\n```bash\r\ncd topdir\r\nflask shell\r\n\r\n# in 0.12.2\r\nError: The file/path provided (app.py) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py\r\n\r\n# n 0.13.dev\r\nError: Could not import \"app\".\"\r\n\r\n```\r\n\r\nLooks like the `run` command is traversing the subfolders to locate an app while the `shell` command is not doing the same.\r\n\r\nand the same applies for the new `routes` on master\r\n\r\n```bash\r\n$ cd topdir\r\n$ flask routes                                                          \r\nUsage: flask routes [OPTIONS]\r\n\r\nError: Could not import \"app\".\"\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.0\r\n* Flask version: 0.12.2 & 0.13.dev (master branch)\r\n* Werkzeug version: 0.14.1\r\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/382416117",
            "html_url": "https://github.com/pallets/flask/issues/2706#issuecomment-382416117",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2706",
            "id": 382416117,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjQxNjExNw==",
            "user": {
                "login": "rochacbruno",
                "id": 458654,
                "node_id": "MDQ6VXNlcjQ1ODY1NA==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/458654?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rochacbruno",
                "html_url": "https://github.com/rochacbruno",
                "followers_url": "https://api.github.com/users/rochacbruno/followers",
                "following_url": "https://api.github.com/users/rochacbruno/following{/other_user}",
                "gists_url": "https://api.github.com/users/rochacbruno/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rochacbruno/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rochacbruno/subscriptions",
                "organizations_url": "https://api.github.com/users/rochacbruno/orgs",
                "repos_url": "https://api.github.com/users/rochacbruno/repos",
                "events_url": "https://api.github.com/users/rochacbruno/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rochacbruno/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-04-18T14:55:33Z",
            "updated_at": "2018-04-18T14:55:33Z",
            "author_association": "CONTRIBUTOR",
            "body": "I just figured out that the behavior of app loading is the same for `run` just the exception behavior is not the same.\r\n\r\nThe `run` command seems to \"run\" an `app.py` but fails later on the first request it throws:\r\n\r\n```\r\nflask.cli.NoAppException\r\nflask.cli.NoAppException: Could not import \"app\".\"\r\n```\r\n\r\nSo the expected behavior is to do the same exception catch in `run` command if `app` cannot be located and fail early in the command and not after first request."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/382416505",
            "html_url": "https://github.com/pallets/flask/issues/2706#issuecomment-382416505",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2706",
            "id": 382416505,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjQxNjUwNQ==",
            "user": {
                "login": "rochacbruno",
                "id": 458654,
                "node_id": "MDQ6VXNlcjQ1ODY1NA==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/458654?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rochacbruno",
                "html_url": "https://github.com/rochacbruno",
                "followers_url": "https://api.github.com/users/rochacbruno/followers",
                "following_url": "https://api.github.com/users/rochacbruno/following{/other_user}",
                "gists_url": "https://api.github.com/users/rochacbruno/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rochacbruno/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rochacbruno/subscriptions",
                "organizations_url": "https://api.github.com/users/rochacbruno/orgs",
                "repos_url": "https://api.github.com/users/rochacbruno/repos",
                "events_url": "https://api.github.com/users/rochacbruno/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rochacbruno/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-04-18T14:56:39Z",
            "updated_at": "2018-04-18T14:56:39Z",
            "author_association": "CONTRIBUTOR",
            "body": "```\r\nflask.cli.NoAppException\r\nflask.cli.NoAppException: Could not import \"app\".\"\r\n\r\nTraceback (most recent call last)\r\nFile \"/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py\", line 325, in __call__\r\nself._flush_bg_loading_exception()\r\nFile \"/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py\", line 313, in _flush_bg_loading_exception\r\nreraise(*exc_info)\r\nFile \"/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/_compat.py\", line 35, in reraise\r\nraise value\r\nFile \"/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py\", line 302, in _load_app\r\nself._load_unlocked()\r\nFile \"/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py\", line 317, in _load_unlocked\r\nself._app = rv = self.loader()\r\nFile \"/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py\", line 372, in load_app\r\napp = locate_app(self, import_name, name)\r\nFile \"/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py\", line 246, in locate_app\r\nOpen an interactive python shell in this frame'Could not import \"{name}\".\"'.format(name=module_name)\r\nflask.cli.NoAppException: Could not import \"app\".\"\r\n```"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/382417867",
            "html_url": "https://github.com/pallets/flask/issues/2706#issuecomment-382417867",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2706",
            "id": 382417867,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjQxNzg2Nw==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-04-18T15:00:28Z",
            "updated_at": "2018-04-18T15:01:28Z",
            "author_association": "MEMBER",
            "body": "Because the app is `FLASK_APP=appdir/app.py`, or if `appdir` is a package, `appdir.app`. The CLI is not going to try to guess/find what folder a filename is under, you have to point it to the thing."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/382419567",
            "html_url": "https://github.com/pallets/flask/issues/2706#issuecomment-382419567",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2706",
            "id": 382419567,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjQxOTU2Nw==",
            "user": {
                "login": "rochacbruno",
                "id": 458654,
                "node_id": "MDQ6VXNlcjQ1ODY1NA==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/458654?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rochacbruno",
                "html_url": "https://github.com/rochacbruno",
                "followers_url": "https://api.github.com/users/rochacbruno/followers",
                "following_url": "https://api.github.com/users/rochacbruno/following{/other_user}",
                "gists_url": "https://api.github.com/users/rochacbruno/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rochacbruno/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rochacbruno/subscriptions",
                "organizations_url": "https://api.github.com/users/rochacbruno/orgs",
                "repos_url": "https://api.github.com/users/rochacbruno/repos",
                "events_url": "https://api.github.com/users/rochacbruno/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rochacbruno/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-04-18T15:05:13Z",
            "updated_at": "2018-04-18T15:08:55Z",
            "author_association": "CONTRIBUTOR",
            "body": "<strike>@davidism I found the issue is when `--lazy-loader` is enabled, which is the default when `FLASK_DEBUG=1`</strike>\r\n\r\nNow my only concern is that `run` `shell` and `routes` behave differently as `shell` and `routes` has no `lazy-loader` at least this behavior should be documented. "
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/382420154",
            "html_url": "https://github.com/pallets/flask/issues/2706#issuecomment-382420154",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2706",
            "id": 382420154,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjQyMDE1NA==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-04-18T15:06:55Z",
            "updated_at": "2018-04-18T15:10:18Z",
            "author_association": "MEMBER",
            "body": "You're confusing the fact that the CLI will lazily load the module in order to show any import or syntax errors in the debugger and allow reloading in the face of such errors, with the fact that you've provided a path that's not correct.\r\n\r\nThe CLI always lazily loads, it's just that most commands need the app immediately and so the import is resolved immediately."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/382421450",
            "html_url": "https://github.com/pallets/flask/issues/2706#issuecomment-382421450",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2706",
            "id": 382421450,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjQyMTQ1MA==",
            "user": {
                "login": "rochacbruno",
                "id": 458654,
                "node_id": "MDQ6VXNlcjQ1ODY1NA==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/458654?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rochacbruno",
                "html_url": "https://github.com/rochacbruno",
                "followers_url": "https://api.github.com/users/rochacbruno/followers",
                "following_url": "https://api.github.com/users/rochacbruno/following{/other_user}",
                "gists_url": "https://api.github.com/users/rochacbruno/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rochacbruno/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rochacbruno/subscriptions",
                "organizations_url": "https://api.github.com/users/rochacbruno/orgs",
                "repos_url": "https://api.github.com/users/rochacbruno/repos",
                "events_url": "https://api.github.com/users/rochacbruno/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rochacbruno/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-04-18T15:10:36Z",
            "updated_at": "2018-04-18T15:11:37Z",
            "author_association": "CONTRIBUTOR",
            "body": "Exactly!\r\n\r\nThe issue that I am reporting is that `people can get confused` when running `flask run` and see `app is running` while it is not (because it will be `lazily loaded` and then run `flask shell` and get immediate error.\r\n\r\n@davidism maybe adding message?\r\n\r\ninsted of:\r\n\r\n```bash\r\n$ flask run                                                    \r\n * Serving Flask app \"app.py\"\r\n```\r\n\r\nIn such case change to:\r\n\r\n```bash\r\n$ flask run \r\n * Serving Flask app WARNING: \"app.py\" will be lazily loaded!!!\r\n\r\n```\r\n\r\n "
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/382426313",
            "html_url": "https://github.com/pallets/flask/issues/2706#issuecomment-382426313",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2706",
            "id": 382426313,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MjQyNjMxMw==",
            "user": {
                "login": "rochacbruno",
                "id": 458654,
                "node_id": "MDQ6VXNlcjQ1ODY1NA==",
                "avatar_url": "https://avatars2.githubusercontent.com/u/458654?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rochacbruno",
                "html_url": "https://github.com/rochacbruno",
                "followers_url": "https://api.github.com/users/rochacbruno/followers",
                "following_url": "https://api.github.com/users/rochacbruno/following{/other_user}",
                "gists_url": "https://api.github.com/users/rochacbruno/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rochacbruno/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rochacbruno/subscriptions",
                "organizations_url": "https://api.github.com/users/rochacbruno/orgs",
                "repos_url": "https://api.github.com/users/rochacbruno/repos",
                "events_url": "https://api.github.com/users/rochacbruno/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rochacbruno/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-04-18T15:24:43Z",
            "updated_at": "2018-04-18T15:24:43Z",
            "author_association": "CONTRIBUTOR",
            "body": "```bash\r\n$ flask run                                                                    \r\n * Serving Flask app \"app.py\"\r\n * Environment: development\r\n * Debug mode: on\r\n * Starting in lazy loader mode\r\n * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\r\n * Restarting with stat\r\n * Starting in lazy loader mode\r\n * Debugger is active!\r\n * Debugger PIN: 189-281-652\r\n\r\n```"
        }
    ]
}