{
    "url": "https://api.github.com/repos/pallets/flask/issues/2788",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/2788/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/2788/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/2788/events",
    "html_url": "https://github.com/pallets/flask/issues/2788",
    "id": 323972333,
    "node_id": "MDU6SXNzdWUzMjM5NzIzMzM=",
    "number": 2788,
    "title": "Log level being ignored and example in docs broken",
    "user": {
        "login": "manoadamro",
        "id": 29605020,
        "node_id": "MDQ6VXNlcjI5NjA1MDIw",
        "avatar_url": "https://avatars2.githubusercontent.com/u/29605020?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/manoadamro",
        "html_url": "https://github.com/manoadamro",
        "followers_url": "https://api.github.com/users/manoadamro/followers",
        "following_url": "https://api.github.com/users/manoadamro/following{/other_user}",
        "gists_url": "https://api.github.com/users/manoadamro/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/manoadamro/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/manoadamro/subscriptions",
        "organizations_url": "https://api.github.com/users/manoadamro/orgs",
        "repos_url": "https://api.github.com/users/manoadamro/repos",
        "events_url": "https://api.github.com/users/manoadamro/events{/privacy}",
        "received_events_url": "https://api.github.com/users/manoadamro/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 5,
    "created_at": "2018-05-17T10:55:38Z",
    "updated_at": "2019-10-23T04:32:54Z",
    "closed_at": "2018-05-17T12:46:47Z",
    "author_association": "NONE",
    "body": "Using the example in the docs:\r\n\r\n```python\r\nimport flask\r\nimport logging.config\r\n\r\nlogging.config.dictConfig({\r\n    'version': 1,\r\n    'formatters': {'default': {\r\n        'format': '[%(asctime)s] %(levelname)s in %(module)s: %(message)s',\r\n    }},\r\n    'handlers': {'wsgi': {\r\n        'class': 'logging.StreamHandler',\r\n        'stream': 'ext://flask.logging.wsgi_errors_stream',\r\n        'formatter': 'default'\r\n    }},\r\n    'root': {\r\n        'level': 'INFO',\r\n        'handlers': ['wsgi']\r\n    }\r\n})\r\n\r\napp = flask.Flask(__name__)\r\n```\r\n\r\nproduces the following error:\r\n```\r\nValueError: Unable to configure handler 'wsgi': Cannot resolve 'flask.logging.wsgi_errors_stream': No module named 'flask.logging.wsgi_errors_stream'; 'flask.logging' is not a package\r\n```\r\n\r\nchanging `ext://flask.logging.wsgi_errors_stream` to `stdout` stops the error, but log level is still ignored.\r\n\r\nUsing the following:\r\n```python\r\nimport flask\r\nimport logging.config\r\n\r\nlogging.config.dictConfig({\r\n    'version': 1,\r\n    'formatters': {\r\n        'default': {\r\n            'format': '[%(asctime)s] %(levelname)s in %(module)s: %(message)s',\r\n        }\r\n    },\r\n    'handlers': {\r\n        'wsgi': {\r\n            'class': 'logging.StreamHandler',\r\n            'stream': 'stdout',\r\n            'formatter': 'default',\r\n        }\r\n    },\r\n    'root': {\r\n        'level': 'DEBUG',\r\n        'handlers': ['wsgi']\r\n    }\r\n})\r\n\r\n\r\napp = flask.Flask(__name__)\r\n\r\napp.logger.debug('I WORK')\r\napp.logger.info('I WORK')\r\napp.logger.warning('I WORK')\r\napp.logger.error('I WORK')\r\napp.logger.critical('I WORK')\r\n```\r\n(Note the log level set to `DEBUG`)\r\n\r\nActual Output:\r\n```\r\n[2018-05-17 11:35:20,069] ERROR in __init__: I WORK\r\n[2018-05-17 11:35:20,069] CRITICAL in __init__: I WORK\r\n```\r\n\r\nExpected output:\r\n```\r\n[2018-05-17 11:35:20,069] DEBUG in __init__: I WORK\r\n[2018-05-17 11:35:20,069] INFO in __init__: I WORK\r\n[2018-05-17 11:35:20,069] WARNING in __init__: I WORK\r\n[2018-05-17 11:35:20,069] ERROR in __init__: I WORK\r\n[2018-05-17 11:35:20,069] CRITICAL in __init__: I WORK\r\n```\r\nI have also tried both setting the level in the handler and formatter and calling `app.logger.setLevel('DEBUG')`\r\nneither made any difference.\r\n\r\nTL;DR:\r\n - logging example in docs errors.\r\n - unable to set log level\r\n---\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.4\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/389853984",
            "html_url": "https://github.com/pallets/flask/issues/2788#issuecomment-389853984",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2788",
            "id": 389853984,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4OTg1Mzk4NA==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-05-17T12:46:47Z",
            "updated_at": "2018-05-17T12:47:14Z",
            "author_association": "MEMBER",
            "body": "Copying both your examples exactly, I can't reproduce the issues you describe. Are you sure that you're running with Flask 1.0? Prior to that `wsgi_errors_stream` didn't exist in the same place. You do have an error in your second `dictConfig` where the stream should be [`ext://sys.stdout`](https://docs.python.org/3/library/logging.config.html#access-to-external-objects), but fixing that I get all five lines output."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/389855205",
            "html_url": "https://github.com/pallets/flask/issues/2788#issuecomment-389855205",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2788",
            "id": 389855205,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4OTg1NTIwNQ==",
            "user": {
                "login": "manoadamro",
                "id": 29605020,
                "node_id": "MDQ6VXNlcjI5NjA1MDIw",
                "avatar_url": "https://avatars2.githubusercontent.com/u/29605020?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/manoadamro",
                "html_url": "https://github.com/manoadamro",
                "followers_url": "https://api.github.com/users/manoadamro/followers",
                "following_url": "https://api.github.com/users/manoadamro/following{/other_user}",
                "gists_url": "https://api.github.com/users/manoadamro/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/manoadamro/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/manoadamro/subscriptions",
                "organizations_url": "https://api.github.com/users/manoadamro/orgs",
                "repos_url": "https://api.github.com/users/manoadamro/repos",
                "events_url": "https://api.github.com/users/manoadamro/events{/privacy}",
                "received_events_url": "https://api.github.com/users/manoadamro/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-05-17T12:51:16Z",
            "updated_at": "2018-05-17T12:51:16Z",
            "author_association": "NONE",
            "body": "@davidism running in a virtual env \r\n\r\n```\r\n(env) pip freeze\r\nclick==6.7\r\nFlask==1.0.2\r\nitsdangerous==0.24\r\nJinja2==2.10\r\nMarkupSafe==1.0\r\nWerkzeug==0.14.1\r\n```"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/389856233",
            "html_url": "https://github.com/pallets/flask/issues/2788#issuecomment-389856233",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2788",
            "id": 389856233,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4OTg1NjIzMw==",
            "user": {
                "login": "manoadamro",
                "id": 29605020,
                "node_id": "MDQ6VXNlcjI5NjA1MDIw",
                "avatar_url": "https://avatars2.githubusercontent.com/u/29605020?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/manoadamro",
                "html_url": "https://github.com/manoadamro",
                "followers_url": "https://api.github.com/users/manoadamro/followers",
                "following_url": "https://api.github.com/users/manoadamro/following{/other_user}",
                "gists_url": "https://api.github.com/users/manoadamro/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/manoadamro/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/manoadamro/subscriptions",
                "organizations_url": "https://api.github.com/users/manoadamro/orgs",
                "repos_url": "https://api.github.com/users/manoadamro/repos",
                "events_url": "https://api.github.com/users/manoadamro/events{/privacy}",
                "received_events_url": "https://api.github.com/users/manoadamro/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-05-17T12:54:48Z",
            "updated_at": "2018-05-17T12:54:48Z",
            "author_association": "NONE",
            "body": "@davidism As it turns out, the problem seems to be with pycharm. \r\nIt's telling me its using the environment but clearly, it isn't. \r\n\r\nUsing nano and terminal i can see it does now work as expected.\r\nthanks and sorry for wasting your time."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/389857050",
            "html_url": "https://github.com/pallets/flask/issues/2788#issuecomment-389857050",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2788",
            "id": 389857050,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4OTg1NzA1MA==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-05-17T12:57:40Z",
            "updated_at": "2018-05-17T12:57:40Z",
            "author_association": "MEMBER",
            "body": "I checked the whole thing in PyCharm from the start, and had no issues. Perhaps something's misconfigured in PyCharm related to the terminal or interpreter?"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/389859016",
            "html_url": "https://github.com/pallets/flask/issues/2788#issuecomment-389859016",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/2788",
            "id": 389859016,
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4OTg1OTAxNg==",
            "user": {
                "login": "manoadamro",
                "id": 29605020,
                "node_id": "MDQ6VXNlcjI5NjA1MDIw",
                "avatar_url": "https://avatars2.githubusercontent.com/u/29605020?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/manoadamro",
                "html_url": "https://github.com/manoadamro",
                "followers_url": "https://api.github.com/users/manoadamro/followers",
                "following_url": "https://api.github.com/users/manoadamro/following{/other_user}",
                "gists_url": "https://api.github.com/users/manoadamro/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/manoadamro/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/manoadamro/subscriptions",
                "organizations_url": "https://api.github.com/users/manoadamro/orgs",
                "repos_url": "https://api.github.com/users/manoadamro/repos",
                "events_url": "https://api.github.com/users/manoadamro/events{/privacy}",
                "received_events_url": "https://api.github.com/users/manoadamro/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2018-05-17T13:04:44Z",
            "updated_at": "2018-05-17T13:04:44Z",
            "author_association": "NONE",
            "body": "yeah, the project interpreter is set /myProject/env/bin/python3 (venv for current project), so is my terminal however pycharm is lying to me, its actually using my global interpreter, because it shows a totally different list when i call pip freeze. either way, not you problem, \r\nthanks again."
        }
    ]
}