{
    "url": "https://api.github.com/repos/pallets/flask/issues/3327",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/3327/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/3327/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/3327/events",
    "html_url": "https://github.com/pallets/flask/issues/3327",
    "id": 478993553,
    "node_id": "MDU6SXNzdWU0Nzg5OTM1NTM=",
    "number": 3327,
    "title": "`flask run` in debug mode fails with `No module named C:\\programs\\Python37\\Scripts\\flask`",
    "user": {
        "login": "sorgloomer",
        "id": 5985835,
        "node_id": "MDQ6VXNlcjU5ODU4MzU=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/5985835?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sorgloomer",
        "html_url": "https://github.com/sorgloomer",
        "followers_url": "https://api.github.com/users/sorgloomer/followers",
        "following_url": "https://api.github.com/users/sorgloomer/following{/other_user}",
        "gists_url": "https://api.github.com/users/sorgloomer/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sorgloomer/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sorgloomer/subscriptions",
        "organizations_url": "https://api.github.com/users/sorgloomer/orgs",
        "repos_url": "https://api.github.com/users/sorgloomer/repos",
        "events_url": "https://api.github.com/users/sorgloomer/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sorgloomer/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2019-08-09T13:41:56Z",
    "updated_at": "2019-08-09T14:06:17Z",
    "closed_at": "2019-08-09T14:06:17Z",
    "author_association": "NONE",
    "body": "<!-- **This issue tracker is a tool to address bugs in Flask itself.\r\nPlease use the #pocoo IRC channel on freenode or Stack Overflow for general\r\nquestions about using Flask or issues not related to Flask.** -->\r\n\r\n<!-- If you'd like to report a bug in Flask, fill out the template below. Provide\r\nany extra information that may be useful / related to your problem.\r\nIdeally, create an [MCVE](https://stackoverflow.com/help/mcve), which helps us\r\nunderstand the problem and helps check that it is not caused by something in\r\nyour code. -->\r\n\r\n### How to reproduce\r\n\r\n * Have flask installed\r\n * Open up a terminal in an empty folder\r\n * run `set FLASK_DEBUG=1 && flask run` (yep, its windows)\r\n\r\n### Expected Behavior\r\nFlask should attempt to start in debug mode, should fail with `Error: Failed to find Flask application or factory in module \"app\". Use \"FLASK_APP=app:name to specify one.` or if you have a valid app in the folder it should start normally in debug mode. Should not fail with `No module named C:\\programs\\Python37\\Scripts\\flask`\r\n\r\n### Actual Behavior\r\nFlask fails earlier, with message: `No module named C:\\programs\\Python37\\Scripts\\flask`\r\n\r\n### Console dump\r\n\r\n```\r\nC:\\workspace\\aliz\\temp\\flaskbug>set FLASK_DEBUG=1 && flask run\r\n * Environment: production\r\n   WARNING: This is a development server. Do not use it in a production deployment.\r\n   Use a production WSGI server instead.\r\n * Debug mode: on\r\n * Restarting with stat\r\nc:\\programs\\python37\\python.exe: No module named C:\\programs\\Python37\\Scripts\\flask\r\n```\r\n\r\n### Environment\r\n\r\n```\r\nC:\\workspace\\aliz\\temp\\flaskbug>python --version\r\nPython 3.7.4\r\n\r\nC:\\workspace\\aliz\\temp\\flaskbug>python -m pip show flask\r\nName: Flask\r\nVersion: 1.1.1\r\n...\r\n\r\nC:\\workspace\\aliz\\temp\\flaskbug>python -m pip show Werkzeug\r\nName: Werkzeug\r\nVersion: 0.15.5\r\n...\r\n\r\nC:\\workspace\\aliz\\temp\\flaskbug>python -c \"import platform;print(platform.python_version(), platform.architecture())\"\r\n3.7.4 ('64bit', 'WindowsPE')\r\n```\r\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/519925269",
            "html_url": "https://github.com/pallets/flask/issues/3327#issuecomment-519925269",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3327",
            "id": 519925269,
            "node_id": "MDEyOklzc3VlQ29tbWVudDUxOTkyNTI2OQ==",
            "user": {
                "login": "carc1n0gen",
                "id": 8248986,
                "node_id": "MDQ6VXNlcjgyNDg5ODY=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/8248986?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/carc1n0gen",
                "html_url": "https://github.com/carc1n0gen",
                "followers_url": "https://api.github.com/users/carc1n0gen/followers",
                "following_url": "https://api.github.com/users/carc1n0gen/following{/other_user}",
                "gists_url": "https://api.github.com/users/carc1n0gen/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/carc1n0gen/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/carc1n0gen/subscriptions",
                "organizations_url": "https://api.github.com/users/carc1n0gen/orgs",
                "repos_url": "https://api.github.com/users/carc1n0gen/repos",
                "events_url": "https://api.github.com/users/carc1n0gen/events{/privacy}",
                "received_events_url": "https://api.github.com/users/carc1n0gen/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-08-09T13:46:15Z",
            "updated_at": "2019-08-09T13:46:15Z",
            "author_association": "NONE",
            "body": "I believe this is a known issue.  Try the workaround `set FLASK_DEBUG=1 && python -m flask run`"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/519932507",
            "html_url": "https://github.com/pallets/flask/issues/3327#issuecomment-519932507",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3327",
            "id": 519932507,
            "node_id": "MDEyOklzc3VlQ29tbWVudDUxOTkzMjUwNw==",
            "user": {
                "login": "sorgloomer",
                "id": 5985835,
                "node_id": "MDQ6VXNlcjU5ODU4MzU=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/5985835?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/sorgloomer",
                "html_url": "https://github.com/sorgloomer",
                "followers_url": "https://api.github.com/users/sorgloomer/followers",
                "following_url": "https://api.github.com/users/sorgloomer/following{/other_user}",
                "gists_url": "https://api.github.com/users/sorgloomer/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/sorgloomer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sorgloomer/subscriptions",
                "organizations_url": "https://api.github.com/users/sorgloomer/orgs",
                "repos_url": "https://api.github.com/users/sorgloomer/repos",
                "events_url": "https://api.github.com/users/sorgloomer/events{/privacy}",
                "received_events_url": "https://api.github.com/users/sorgloomer/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-08-09T14:06:17Z",
            "updated_at": "2019-08-09T14:06:17Z",
            "author_association": "NONE",
            "body": "Thanks! The workaround indeed works and suits my usecase. I did not find this issue before, searched again, the closest seems to be this one: https://github.com/pallets/werkzeug/issues/1619 . I will follow up there, and I am closing this one. Thanks again!"
        }
    ]
}