{
    "url": "https://api.github.com/repos/pallets/flask/issues/3331",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/3331/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/3331/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/3331/events",
    "html_url": "https://github.com/pallets/flask/issues/3331",
    "id": 479738816,
    "node_id": "MDU6SXNzdWU0Nzk3Mzg4MTY=",
    "number": 3331,
    "title": "Python debugger can't find module error ",
    "user": {
        "login": "samayo",
        "id": 5304093,
        "node_id": "MDQ6VXNlcjUzMDQwOTM=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5304093?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/samayo",
        "html_url": "https://github.com/samayo",
        "followers_url": "https://api.github.com/users/samayo/followers",
        "following_url": "https://api.github.com/users/samayo/following{/other_user}",
        "gists_url": "https://api.github.com/users/samayo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/samayo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/samayo/subscriptions",
        "organizations_url": "https://api.github.com/users/samayo/orgs",
        "repos_url": "https://api.github.com/users/samayo/repos",
        "events_url": "https://api.github.com/users/samayo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/samayo/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2019-08-12T16:29:22Z",
    "updated_at": "2019-08-12T22:04:26Z",
    "closed_at": "2019-08-12T22:04:26Z",
    "author_association": "NONE",
    "body": "<!-- **This issue tracker is a tool to address bugs in Flask itself.\r\nPlease use the #pocoo IRC channel on freenode or Stack Overflow for general\r\nquestions about using Flask or issues not related to Flask.** -->\r\n\r\n<!-- If you'd like to report a bug in Flask, fill out the template below. Provide\r\nany extra information that may be useful / related to your problem.\r\nIdeally, create an [MCVE](https://stackoverflow.com/help/mcve), which helps us\r\nunderstand the problem and helps check that it is not caused by something in\r\nyour code. -->\r\n\r\n\r\n\r\n### Expected Behavior\r\nApp should run as expected on 127.0.0.1 with debugger mode enabled\r\n\r\n```python\r\n# Paste a minimal example that causes the problem.\r\n# .. E:/web/public/myblog.in/hello.py\r\nfrom flask import Flask\r\napp = Flask(__name__)\r\n\r\n@app.route('/')\r\ndef hello_world():\r\n    return 'Hello, World!'\r\n```\r\nall configs and venv enabled as https://flask.palletsprojects.com/en/1.1.x/quickstart/\r\n```bash\r\nexport FLASK_APP=hello.py\r\n\r\n```\r\n\r\n\r\n### Actual Behavior\r\n<!-- Tell us what happens instead. -->\r\n`flask run` works as expected. I can see the \"Hello world\" without issues, **unless** I enabled debug mode as `export FLASK_ENV=development` in which case if I run `flask run` I get \r\n\r\n```bash\r\n$ flask run                                                                                                                                                                                                        \r\n * Serving Flask app \"hello.py\" (lazy loading)                                                                                                                                                                     \r\n * Environment: development                                                                                                                                                                                        \r\n * Debug mode: on                                                                                                                                                                                                  \r\n * Restarting with stat                                                                                                                                                                                            \r\ne:\\web\\public\\myblog.in\\venv\\scripts\\python.exe: Error while finding module specification for 'E:\\\\web\\\\public\\\\myblog.in\\\\venv\\\\Scripts\\\\flask' (ModuleNotFoundError: No module named 'E:\\\\web\\\\public\\\\myblog')  \r\n```\r\n\r\nYou can see in the last error it says `No module named 'E:\\\\web\\\\public\\\\myblog` (it should be ..`\\\\myblog.in` **(.in)** is missing, maybe that is the issue (bug)\r\n\r\n### Environment\r\n\r\n* Python version: 3.7.1\r\n* Flask version: 1.1.x\r\n* Werkzeug version: 0.15.5\r\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/520612675",
            "html_url": "https://github.com/pallets/flask/issues/3331#issuecomment-520612675",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3331",
            "id": 520612675,
            "node_id": "MDEyOklzc3VlQ29tbWVudDUyMDYxMjY3NQ==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-08-12T22:04:26Z",
            "updated_at": "2019-08-12T22:04:26Z",
            "author_association": "MEMBER",
            "body": "Duplicate of pallets/werkzeug#1619"
        }
    ]
}