{
    "url": "https://api.github.com/repos/pallets/flask/issues/421",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/421/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/421/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/421/events",
    "html_url": "https://github.com/pallets/flask/issues/421",
    "id": 3569596,
    "node_id": "MDU6SXNzdWUzNTY5NTk2",
    "number": 421,
    "title": "pip/virtualenv flaskext import error",
    "user": {
        "login": "davidovich",
        "id": 1440370,
        "node_id": "MDQ6VXNlcjE0NDAzNzA=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/1440370?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/davidovich",
        "html_url": "https://github.com/davidovich",
        "followers_url": "https://api.github.com/users/davidovich/followers",
        "following_url": "https://api.github.com/users/davidovich/following{/other_user}",
        "gists_url": "https://api.github.com/users/davidovich/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/davidovich/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/davidovich/subscriptions",
        "organizations_url": "https://api.github.com/users/davidovich/orgs",
        "repos_url": "https://api.github.com/users/davidovich/repos",
        "events_url": "https://api.github.com/users/davidovich/events{/privacy}",
        "received_events_url": "https://api.github.com/users/davidovich/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 3,
    "created_at": "2012-03-08T18:57:03Z",
    "updated_at": "2014-01-17T10:06:57Z",
    "closed_at": "2012-03-08T19:30:33Z",
    "author_association": "NONE",
    "body": "Found this while searching for a solution: https://github.com/mitsuhiko/flask-babel/issues/19\n\nIn this issue, @ralfonso mentions that he is having trouble importing an editable babel package. I am having this problem too, but with another extension (flask_mongokit). \n\nfrom the python interpreter, if I import: \n\n``` python\nfrom flaskext.mongokit import MongoKit\n```\n\nI get an ImportError: No module named mongokit\n\nWhen I run my tests with nosetests, everything is fine. When I import from ipython, it works too. But running and importing from the plain interpreter fails.\n\nsys.path contains:\n~/.virtualenvs/myflask_project/src/flask-mongokit\n\nI am not sure what is going on, because I know I ran the application before, and since then I pip installed/uninstalled many packages (non-editable).\n\n**NOTE**\n\n**After uninstalling flask-openid, the setup works again as intended. Is something wrong with flask-openid's  setup? Or with the flask exthook functionality?**\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/4400393",
            "html_url": "https://github.com/pallets/flask/issues/421#issuecomment-4400393",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/421",
            "id": 4400393,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MDAzOTM=",
            "user": {
                "login": "rduplain",
                "id": 36428,
                "node_id": "MDQ6VXNlcjM2NDI4",
                "avatar_url": "https://avatars1.githubusercontent.com/u/36428?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rduplain",
                "html_url": "https://github.com/rduplain",
                "followers_url": "https://api.github.com/users/rduplain/followers",
                "following_url": "https://api.github.com/users/rduplain/following{/other_user}",
                "gists_url": "https://api.github.com/users/rduplain/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rduplain/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rduplain/subscriptions",
                "organizations_url": "https://api.github.com/users/rduplain/orgs",
                "repos_url": "https://api.github.com/users/rduplain/repos",
                "events_url": "https://api.github.com/users/rduplain/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rduplain/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2012-03-08T19:30:33Z",
            "updated_at": "2012-03-08T19:30:33Z",
            "author_association": "CONTRIBUTOR",
            "body": "This is a problem with namespace packages.  When you get this kind of error, you'll find in your site-packages an extension which was installed at \"flaskext\" and not inside a directory that gets listed in a .pth file.  Namespace packages require a very specific `__init__.py`, which the broken installation at \"flaskext\" does not provide.\n\nWe discussed this issue upstream, but ultimately abandoned namespace packages, preferring flask_extension.py instead of flaskext/extension.py.  The full discussion is here:\n\nhttp://flask.pocoo.org/mailinglist/archive/2011/9/25/ann-migration-to-new-extension-distribution/\n\nThe workaround is to find the offending package installation, uninstall it, and reinstall it.  It's a bug somewhere in the packaging tools.  When most frustrated, I find a pure `python setup.py install` works.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/4401873",
            "html_url": "https://github.com/pallets/flask/issues/421#issuecomment-4401873",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/421",
            "id": 4401873,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MDE4NzM=",
            "user": {
                "login": "davidovich",
                "id": 1440370,
                "node_id": "MDQ6VXNlcjE0NDAzNzA=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/1440370?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidovich",
                "html_url": "https://github.com/davidovich",
                "followers_url": "https://api.github.com/users/davidovich/followers",
                "following_url": "https://api.github.com/users/davidovich/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidovich/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidovich/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidovich/subscriptions",
                "organizations_url": "https://api.github.com/users/davidovich/orgs",
                "repos_url": "https://api.github.com/users/davidovich/repos",
                "events_url": "https://api.github.com/users/davidovich/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidovich/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2012-03-08T20:46:38Z",
            "updated_at": "2012-03-08T20:46:38Z",
            "author_association": "NONE",
            "body": "I also tried with flask-oauth, which breaks my --editable package in the same way. As you mention, it installs a flaskext directory in site-packages. What kind of changes are necessary in the setup script in order to fix the issue ? would replacing the \n\n``` python\npackages = [flaskext],\nnamespace_packages=['flaskext']\n```\n\nby\n\n``` python\npy_modules=['flask_openid']\n```\n\nand naming the extension appropriately work ?\n\nIt seems that these extensions (flask-openid and flask-oauth, and maybe others) do not follow the new extensions convention am I right? Should I submit a pull request?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/4427472",
            "html_url": "https://github.com/pallets/flask/issues/421#issuecomment-4427472",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/421",
            "id": 4427472,
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ0Mjc0NzI=",
            "user": {
                "login": "rduplain",
                "id": 36428,
                "node_id": "MDQ6VXNlcjM2NDI4",
                "avatar_url": "https://avatars1.githubusercontent.com/u/36428?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/rduplain",
                "html_url": "https://github.com/rduplain",
                "followers_url": "https://api.github.com/users/rduplain/followers",
                "following_url": "https://api.github.com/users/rduplain/following{/other_user}",
                "gists_url": "https://api.github.com/users/rduplain/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/rduplain/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rduplain/subscriptions",
                "organizations_url": "https://api.github.com/users/rduplain/orgs",
                "repos_url": "https://api.github.com/users/rduplain/repos",
                "events_url": "https://api.github.com/users/rduplain/events{/privacy}",
                "received_events_url": "https://api.github.com/users/rduplain/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2012-03-10T00:29:50Z",
            "updated_at": "2012-03-10T00:29:50Z",
            "author_association": "CONTRIBUTOR",
            "body": "You have the right approach in the namespace update, but a pull request would have to be accepted before any other changes since it's a very disruptive change.\n\nFor an example:\nhttps://github.com/dag/flask-zodb/\n\nI expect the overall namespace upgrade to take a very long time.  I'm pretty sure `easy_install` (pure setuptools) does not exhibit this installation bug, only pip (not sure which version or whether fixed).\n"
        }
    ]
}